/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddMemberToAccountGroup struct for AddMemberToAccountGroup
type AddMemberToAccountGroup struct {
	// The ID of the account that will be added as a member to the group.
	AccountId string `json:"AccountId"`
}

// NewAddMemberToAccountGroup instantiates a new AddMemberToAccountGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddMemberToAccountGroup(accountId string) *AddMemberToAccountGroup {
	this := AddMemberToAccountGroup{}
	this.AccountId = accountId
	return &this
}

// NewAddMemberToAccountGroupWithDefaults instantiates a new AddMemberToAccountGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddMemberToAccountGroupWithDefaults() *AddMemberToAccountGroup {
	this := AddMemberToAccountGroup{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AddMemberToAccountGroup) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AddMemberToAccountGroup) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AddMemberToAccountGroup) SetAccountId(v string) {
	o.AccountId = v
}

func (o AddMemberToAccountGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["AccountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAddMemberToAccountGroup struct {
	value *AddMemberToAccountGroup
	isSet bool
}

func (v NullableAddMemberToAccountGroup) Get() *AddMemberToAccountGroup {
	return v.value
}

func (v *NullableAddMemberToAccountGroup) Set(val *AddMemberToAccountGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableAddMemberToAccountGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableAddMemberToAccountGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddMemberToAccountGroup(val *AddMemberToAccountGroup) *NullableAddMemberToAccountGroup {
	return &NullableAddMemberToAccountGroup{value: val, isSet: true}
}

func (v NullableAddMemberToAccountGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddMemberToAccountGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


