/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DuplicatePlatform struct for DuplicatePlatform
type DuplicatePlatform struct {
	// Display name of the new platform
	Name string `json:"Name"`
	// Description of the new platform
	Description *string `json:"Description,omitempty"`
}

// NewDuplicatePlatform instantiates a new DuplicatePlatform object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDuplicatePlatform(name string) *DuplicatePlatform {
	this := DuplicatePlatform{}
	this.Name = name
	return &this
}

// NewDuplicatePlatformWithDefaults instantiates a new DuplicatePlatform object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDuplicatePlatformWithDefaults() *DuplicatePlatform {
	this := DuplicatePlatform{}
	return &this
}

// GetName returns the Name field value
func (o *DuplicatePlatform) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DuplicatePlatform) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DuplicatePlatform) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DuplicatePlatform) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DuplicatePlatform) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DuplicatePlatform) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DuplicatePlatform) SetDescription(v string) {
	o.Description = &v
}

func (o DuplicatePlatform) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["Description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableDuplicatePlatform struct {
	value *DuplicatePlatform
	isSet bool
}

func (v NullableDuplicatePlatform) Get() *DuplicatePlatform {
	return v.value
}

func (v *NullableDuplicatePlatform) Set(val *DuplicatePlatform) {
	v.value = val
	v.isSet = true
}

func (v NullableDuplicatePlatform) IsSet() bool {
	return v.isSet
}

func (v *NullableDuplicatePlatform) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDuplicatePlatform(val *DuplicatePlatform) *NullableDuplicatePlatform {
	return &NullableDuplicatePlatform{value: val, isSet: true}
}

func (v NullableDuplicatePlatform) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDuplicatePlatform) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


