/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AuthenticationMethodsResponse struct for AuthenticationMethodsResponse
type AuthenticationMethodsResponse struct {
	Methods []AuthenticationMethod `json:"Methods,omitempty"`
}

// NewAuthenticationMethodsResponse instantiates a new AuthenticationMethodsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationMethodsResponse() *AuthenticationMethodsResponse {
	this := AuthenticationMethodsResponse{}
	return &this
}

// NewAuthenticationMethodsResponseWithDefaults instantiates a new AuthenticationMethodsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationMethodsResponseWithDefaults() *AuthenticationMethodsResponse {
	this := AuthenticationMethodsResponse{}
	return &this
}

// GetMethods returns the Methods field value if set, zero value otherwise.
func (o *AuthenticationMethodsResponse) GetMethods() []AuthenticationMethod {
	if o == nil || o.Methods == nil {
		var ret []AuthenticationMethod
		return ret
	}
	return o.Methods
}

// GetMethodsOk returns a tuple with the Methods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationMethodsResponse) GetMethodsOk() ([]AuthenticationMethod, bool) {
	if o == nil || o.Methods == nil {
		return nil, false
	}
	return o.Methods, true
}

// HasMethods returns a boolean if a field has been set.
func (o *AuthenticationMethodsResponse) HasMethods() bool {
	if o != nil && o.Methods != nil {
		return true
	}

	return false
}

// SetMethods gets a reference to the given []AuthenticationMethod and assigns it to the Methods field.
func (o *AuthenticationMethodsResponse) SetMethods(v []AuthenticationMethod) {
	o.Methods = v
}

func (o AuthenticationMethodsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Methods != nil {
		toSerialize["Methods"] = o.Methods
	}
	return json.Marshal(toSerialize)
}

type NullableAuthenticationMethodsResponse struct {
	value *AuthenticationMethodsResponse
	isSet bool
}

func (v NullableAuthenticationMethodsResponse) Get() *AuthenticationMethodsResponse {
	return v.value
}

func (v *NullableAuthenticationMethodsResponse) Set(val *AuthenticationMethodsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationMethodsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationMethodsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationMethodsResponse(val *AuthenticationMethodsResponse) *NullableAuthenticationMethodsResponse {
	return &NullableAuthenticationMethodsResponse{value: val, isSet: true}
}

func (v NullableAuthenticationMethodsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationMethodsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


