/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountGroupMember struct for AccountGroupMember
type AccountGroupMember struct {
	AccountID *string `json:"AccountID,omitempty"`
	SafeName *string `json:"SafeName,omitempty"`
	PlatformID *string `json:"PlatformID,omitempty"`
	Address *string `json:"Address,omitempty"`
	UserName *string `json:"UserName,omitempty"`
}

// NewAccountGroupMember instantiates a new AccountGroupMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGroupMember() *AccountGroupMember {
	this := AccountGroupMember{}
	return &this
}

// NewAccountGroupMemberWithDefaults instantiates a new AccountGroupMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGroupMemberWithDefaults() *AccountGroupMember {
	this := AccountGroupMember{}
	return &this
}

// GetAccountID returns the AccountID field value if set, zero value otherwise.
func (o *AccountGroupMember) GetAccountID() string {
	if o == nil || o.AccountID == nil {
		var ret string
		return ret
	}
	return *o.AccountID
}

// GetAccountIDOk returns a tuple with the AccountID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupMember) GetAccountIDOk() (*string, bool) {
	if o == nil || o.AccountID == nil {
		return nil, false
	}
	return o.AccountID, true
}

// HasAccountID returns a boolean if a field has been set.
func (o *AccountGroupMember) HasAccountID() bool {
	if o != nil && o.AccountID != nil {
		return true
	}

	return false
}

// SetAccountID gets a reference to the given string and assigns it to the AccountID field.
func (o *AccountGroupMember) SetAccountID(v string) {
	o.AccountID = &v
}

// GetSafeName returns the SafeName field value if set, zero value otherwise.
func (o *AccountGroupMember) GetSafeName() string {
	if o == nil || o.SafeName == nil {
		var ret string
		return ret
	}
	return *o.SafeName
}

// GetSafeNameOk returns a tuple with the SafeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupMember) GetSafeNameOk() (*string, bool) {
	if o == nil || o.SafeName == nil {
		return nil, false
	}
	return o.SafeName, true
}

// HasSafeName returns a boolean if a field has been set.
func (o *AccountGroupMember) HasSafeName() bool {
	if o != nil && o.SafeName != nil {
		return true
	}

	return false
}

// SetSafeName gets a reference to the given string and assigns it to the SafeName field.
func (o *AccountGroupMember) SetSafeName(v string) {
	o.SafeName = &v
}

// GetPlatformID returns the PlatformID field value if set, zero value otherwise.
func (o *AccountGroupMember) GetPlatformID() string {
	if o == nil || o.PlatformID == nil {
		var ret string
		return ret
	}
	return *o.PlatformID
}

// GetPlatformIDOk returns a tuple with the PlatformID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupMember) GetPlatformIDOk() (*string, bool) {
	if o == nil || o.PlatformID == nil {
		return nil, false
	}
	return o.PlatformID, true
}

// HasPlatformID returns a boolean if a field has been set.
func (o *AccountGroupMember) HasPlatformID() bool {
	if o != nil && o.PlatformID != nil {
		return true
	}

	return false
}

// SetPlatformID gets a reference to the given string and assigns it to the PlatformID field.
func (o *AccountGroupMember) SetPlatformID(v string) {
	o.PlatformID = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *AccountGroupMember) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupMember) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *AccountGroupMember) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *AccountGroupMember) SetAddress(v string) {
	o.Address = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *AccountGroupMember) GetUserName() string {
	if o == nil || o.UserName == nil {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupMember) GetUserNameOk() (*string, bool) {
	if o == nil || o.UserName == nil {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *AccountGroupMember) HasUserName() bool {
	if o != nil && o.UserName != nil {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *AccountGroupMember) SetUserName(v string) {
	o.UserName = &v
}

func (o AccountGroupMember) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountID != nil {
		toSerialize["AccountID"] = o.AccountID
	}
	if o.SafeName != nil {
		toSerialize["SafeName"] = o.SafeName
	}
	if o.PlatformID != nil {
		toSerialize["PlatformID"] = o.PlatformID
	}
	if o.Address != nil {
		toSerialize["Address"] = o.Address
	}
	if o.UserName != nil {
		toSerialize["UserName"] = o.UserName
	}
	return json.Marshal(toSerialize)
}

type NullableAccountGroupMember struct {
	value *AccountGroupMember
	isSet bool
}

func (v NullableAccountGroupMember) Get() *AccountGroupMember {
	return v.value
}

func (v *NullableAccountGroupMember) Set(val *AccountGroupMember) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGroupMember) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGroupMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGroupMember(val *AccountGroupMember) *NullableAccountGroupMember {
	return &NullableAccountGroupMember{value: val, isSet: true}
}

func (v NullableAccountGroupMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGroupMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


