/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetTargetPlatformsRequest struct for GetTargetPlatformsRequest
type GetTargetPlatformsRequest struct {
	Filter *string `json:"filter,omitempty"`
	Search *string `json:"Search,omitempty"`
}

// NewGetTargetPlatformsRequest instantiates a new GetTargetPlatformsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTargetPlatformsRequest() *GetTargetPlatformsRequest {
	this := GetTargetPlatformsRequest{}
	return &this
}

// NewGetTargetPlatformsRequestWithDefaults instantiates a new GetTargetPlatformsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTargetPlatformsRequestWithDefaults() *GetTargetPlatformsRequest {
	this := GetTargetPlatformsRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *GetTargetPlatformsRequest) GetFilter() string {
	if o == nil || o.Filter == nil {
		var ret string
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTargetPlatformsRequest) GetFilterOk() (*string, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *GetTargetPlatformsRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given string and assigns it to the Filter field.
func (o *GetTargetPlatformsRequest) SetFilter(v string) {
	o.Filter = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *GetTargetPlatformsRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTargetPlatformsRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *GetTargetPlatformsRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *GetTargetPlatformsRequest) SetSearch(v string) {
	o.Search = &v
}

func (o GetTargetPlatformsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Search != nil {
		toSerialize["Search"] = o.Search
	}
	return json.Marshal(toSerialize)
}

type NullableGetTargetPlatformsRequest struct {
	value *GetTargetPlatformsRequest
	isSet bool
}

func (v NullableGetTargetPlatformsRequest) Get() *GetTargetPlatformsRequest {
	return v.value
}

func (v *NullableGetTargetPlatformsRequest) Set(val *GetTargetPlatformsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTargetPlatformsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTargetPlatformsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTargetPlatformsRequest(val *GetTargetPlatformsRequest) *NullableGetTargetPlatformsRequest {
	return &NullableGetTargetPlatformsRequest{value: val, isSet: true}
}

func (v NullableGetTargetPlatformsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTargetPlatformsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


