/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PlatformModel struct for PlatformModel
type PlatformModel struct {
	General *General `json:"general,omitempty"`
	Properties *Properties `json:"properties,omitempty"`
	// A list of all linked accounts types that are relevant for the platform, each linked account has a name and a display name
	LinkedAccounts []Identity `json:"linkedAccounts,omitempty"`
	CredentialsManagement *CredentialsManagement `json:"credentialsManagement,omitempty"`
	SessionManagement *SessionManagement `json:"sessionManagement,omitempty"`
	PrivilegedAccessWorkflows *PrivilegedAccessWorkflows `json:"privilegedAccessWorkflows,omitempty"`
}

// NewPlatformModel instantiates a new PlatformModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformModel() *PlatformModel {
	this := PlatformModel{}
	return &this
}

// NewPlatformModelWithDefaults instantiates a new PlatformModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformModelWithDefaults() *PlatformModel {
	this := PlatformModel{}
	return &this
}

// GetGeneral returns the General field value if set, zero value otherwise.
func (o *PlatformModel) GetGeneral() General {
	if o == nil || o.General == nil {
		var ret General
		return ret
	}
	return *o.General
}

// GetGeneralOk returns a tuple with the General field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformModel) GetGeneralOk() (*General, bool) {
	if o == nil || o.General == nil {
		return nil, false
	}
	return o.General, true
}

// HasGeneral returns a boolean if a field has been set.
func (o *PlatformModel) HasGeneral() bool {
	if o != nil && o.General != nil {
		return true
	}

	return false
}

// SetGeneral gets a reference to the given General and assigns it to the General field.
func (o *PlatformModel) SetGeneral(v General) {
	o.General = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *PlatformModel) GetProperties() Properties {
	if o == nil || o.Properties == nil {
		var ret Properties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformModel) GetPropertiesOk() (*Properties, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *PlatformModel) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given Properties and assigns it to the Properties field.
func (o *PlatformModel) SetProperties(v Properties) {
	o.Properties = &v
}

// GetLinkedAccounts returns the LinkedAccounts field value if set, zero value otherwise.
func (o *PlatformModel) GetLinkedAccounts() []Identity {
	if o == nil || o.LinkedAccounts == nil {
		var ret []Identity
		return ret
	}
	return o.LinkedAccounts
}

// GetLinkedAccountsOk returns a tuple with the LinkedAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformModel) GetLinkedAccountsOk() ([]Identity, bool) {
	if o == nil || o.LinkedAccounts == nil {
		return nil, false
	}
	return o.LinkedAccounts, true
}

// HasLinkedAccounts returns a boolean if a field has been set.
func (o *PlatformModel) HasLinkedAccounts() bool {
	if o != nil && o.LinkedAccounts != nil {
		return true
	}

	return false
}

// SetLinkedAccounts gets a reference to the given []Identity and assigns it to the LinkedAccounts field.
func (o *PlatformModel) SetLinkedAccounts(v []Identity) {
	o.LinkedAccounts = v
}

// GetCredentialsManagement returns the CredentialsManagement field value if set, zero value otherwise.
func (o *PlatformModel) GetCredentialsManagement() CredentialsManagement {
	if o == nil || o.CredentialsManagement == nil {
		var ret CredentialsManagement
		return ret
	}
	return *o.CredentialsManagement
}

// GetCredentialsManagementOk returns a tuple with the CredentialsManagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformModel) GetCredentialsManagementOk() (*CredentialsManagement, bool) {
	if o == nil || o.CredentialsManagement == nil {
		return nil, false
	}
	return o.CredentialsManagement, true
}

// HasCredentialsManagement returns a boolean if a field has been set.
func (o *PlatformModel) HasCredentialsManagement() bool {
	if o != nil && o.CredentialsManagement != nil {
		return true
	}

	return false
}

// SetCredentialsManagement gets a reference to the given CredentialsManagement and assigns it to the CredentialsManagement field.
func (o *PlatformModel) SetCredentialsManagement(v CredentialsManagement) {
	o.CredentialsManagement = &v
}

// GetSessionManagement returns the SessionManagement field value if set, zero value otherwise.
func (o *PlatformModel) GetSessionManagement() SessionManagement {
	if o == nil || o.SessionManagement == nil {
		var ret SessionManagement
		return ret
	}
	return *o.SessionManagement
}

// GetSessionManagementOk returns a tuple with the SessionManagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformModel) GetSessionManagementOk() (*SessionManagement, bool) {
	if o == nil || o.SessionManagement == nil {
		return nil, false
	}
	return o.SessionManagement, true
}

// HasSessionManagement returns a boolean if a field has been set.
func (o *PlatformModel) HasSessionManagement() bool {
	if o != nil && o.SessionManagement != nil {
		return true
	}

	return false
}

// SetSessionManagement gets a reference to the given SessionManagement and assigns it to the SessionManagement field.
func (o *PlatformModel) SetSessionManagement(v SessionManagement) {
	o.SessionManagement = &v
}

// GetPrivilegedAccessWorkflows returns the PrivilegedAccessWorkflows field value if set, zero value otherwise.
func (o *PlatformModel) GetPrivilegedAccessWorkflows() PrivilegedAccessWorkflows {
	if o == nil || o.PrivilegedAccessWorkflows == nil {
		var ret PrivilegedAccessWorkflows
		return ret
	}
	return *o.PrivilegedAccessWorkflows
}

// GetPrivilegedAccessWorkflowsOk returns a tuple with the PrivilegedAccessWorkflows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformModel) GetPrivilegedAccessWorkflowsOk() (*PrivilegedAccessWorkflows, bool) {
	if o == nil || o.PrivilegedAccessWorkflows == nil {
		return nil, false
	}
	return o.PrivilegedAccessWorkflows, true
}

// HasPrivilegedAccessWorkflows returns a boolean if a field has been set.
func (o *PlatformModel) HasPrivilegedAccessWorkflows() bool {
	if o != nil && o.PrivilegedAccessWorkflows != nil {
		return true
	}

	return false
}

// SetPrivilegedAccessWorkflows gets a reference to the given PrivilegedAccessWorkflows and assigns it to the PrivilegedAccessWorkflows field.
func (o *PlatformModel) SetPrivilegedAccessWorkflows(v PrivilegedAccessWorkflows) {
	o.PrivilegedAccessWorkflows = &v
}

func (o PlatformModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.General != nil {
		toSerialize["general"] = o.General
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	if o.LinkedAccounts != nil {
		toSerialize["linkedAccounts"] = o.LinkedAccounts
	}
	if o.CredentialsManagement != nil {
		toSerialize["credentialsManagement"] = o.CredentialsManagement
	}
	if o.SessionManagement != nil {
		toSerialize["sessionManagement"] = o.SessionManagement
	}
	if o.PrivilegedAccessWorkflows != nil {
		toSerialize["privilegedAccessWorkflows"] = o.PrivilegedAccessWorkflows
	}
	return json.Marshal(toSerialize)
}

type NullablePlatformModel struct {
	value *PlatformModel
	isSet bool
}

func (v NullablePlatformModel) Get() *PlatformModel {
	return v.value
}

func (v *NullablePlatformModel) Set(val *PlatformModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformModel(val *PlatformModel) *NullablePlatformModel {
	return &NullablePlatformModel{value: val, isSet: true}
}

func (v NullablePlatformModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


