/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AutomaticOnboardingRuleData struct for AutomaticOnboardingRuleData
type AutomaticOnboardingRuleData struct {
	// A numeric identifier for the rule, assigned by the system.
	RuleId *int64 `json:"RuleId,omitempty"`
	// Name of the rule. This is either auto-generated or specified by the user when the rule is created.
	RuleName *string `json:"RuleName,omitempty"`
	// A description of the rule.
	RuleDescription *string `json:"RuleDescription,omitempty"`
	// The order in which the rules are run.  Rules are ordered based on creation time.The most recently created rule will have a precedence of 1, the next most recently created rule will have a precedence of 2, and so on.  During discovery, when a new account is discovered, it is first compared to the rule with precedence 1 to check if the account matches the rule's filters. If so, the account is onboarded according to the rule. If not, the account is compared to the next rule by precedence, and so on.
	RulePrecedence *int32 `json:"RulePrecedence,omitempty"`
	// The ID of the platform that the onboarded account will be associated with.
	TargetPlatformId *string `json:"TargetPlatformId,omitempty"`
	// Device type of the Target Platform
	TargetDeviceType *string `json:"TargetDeviceType,omitempty"`
	// The name of the Safe where the onboarded account will be stored.  Security requirement: If the user is not an owner of the Safe, a null string will be returned.
	TargetSafeName *string `json:"TargetSafeName,omitempty"`
	// Whether or not only accounts with the following admin ID will be onboarded automatically according to this rule.  Unix accounts whose UID is 0.  Windows accounts whose SID ends with 500.  If this value is set to false, the admin ID will not be considered and all accounts matching the rule will be onboarded.
	IsAdminIDFilter *bool `json:"IsAdminIDFilter,omitempty"`
	// The Machine Type by which to filter.
	MachineTypeFilter *string `json:"MachineTypeFilter,omitempty"`
	// The System Type by which to filter.
	SystemTypeFilter *string `json:"SystemTypeFilter,omitempty"`
	// The date and time when the rule was created.
	CreationTime *int32 `json:"CreationTime,omitempty"`
	// The name of the user by which to filter.
	UserNameFilter *string `json:"UserNameFilter,omitempty"`
	// The method to use when applying the username filter.
	UserNameMethod *string `json:"UserNameMethod,omitempty"`
	// The IP address or DNS domain name of the machine by which to filter.
	AddressFilter *string `json:"AddressFilter,omitempty"`
	// The method to use when applying the address filter.
	AddressMethod *string `json:"AddressMethod,omitempty"`
	// 
	AccountTypeFilter *string `json:"AccountTypeFilter,omitempty"`
	// Filter for privileged or non-privileged accounts.
	AccountCategoryFilter *string `json:"AccountCategoryFilter,omitempty"`
	// 
	ReconcileAccountId *string `json:"ReconcileAccountId,omitempty"`
	// The last time that an account was successfully onboarded using this rule.
	LastOnboardedTime *int32 `json:"LastOnboardedTime,omitempty"`
}

// NewAutomaticOnboardingRuleData instantiates a new AutomaticOnboardingRuleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutomaticOnboardingRuleData() *AutomaticOnboardingRuleData {
	this := AutomaticOnboardingRuleData{}
	return &this
}

// NewAutomaticOnboardingRuleDataWithDefaults instantiates a new AutomaticOnboardingRuleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutomaticOnboardingRuleDataWithDefaults() *AutomaticOnboardingRuleData {
	this := AutomaticOnboardingRuleData{}
	return &this
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetRuleId() int64 {
	if o == nil || o.RuleId == nil {
		var ret int64
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetRuleIdOk() (*int64, bool) {
	if o == nil || o.RuleId == nil {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasRuleId() bool {
	if o != nil && o.RuleId != nil {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given int64 and assigns it to the RuleId field.
func (o *AutomaticOnboardingRuleData) SetRuleId(v int64) {
	o.RuleId = &v
}

// GetRuleName returns the RuleName field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetRuleName() string {
	if o == nil || o.RuleName == nil {
		var ret string
		return ret
	}
	return *o.RuleName
}

// GetRuleNameOk returns a tuple with the RuleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetRuleNameOk() (*string, bool) {
	if o == nil || o.RuleName == nil {
		return nil, false
	}
	return o.RuleName, true
}

// HasRuleName returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasRuleName() bool {
	if o != nil && o.RuleName != nil {
		return true
	}

	return false
}

// SetRuleName gets a reference to the given string and assigns it to the RuleName field.
func (o *AutomaticOnboardingRuleData) SetRuleName(v string) {
	o.RuleName = &v
}

// GetRuleDescription returns the RuleDescription field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetRuleDescription() string {
	if o == nil || o.RuleDescription == nil {
		var ret string
		return ret
	}
	return *o.RuleDescription
}

// GetRuleDescriptionOk returns a tuple with the RuleDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetRuleDescriptionOk() (*string, bool) {
	if o == nil || o.RuleDescription == nil {
		return nil, false
	}
	return o.RuleDescription, true
}

// HasRuleDescription returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasRuleDescription() bool {
	if o != nil && o.RuleDescription != nil {
		return true
	}

	return false
}

// SetRuleDescription gets a reference to the given string and assigns it to the RuleDescription field.
func (o *AutomaticOnboardingRuleData) SetRuleDescription(v string) {
	o.RuleDescription = &v
}

// GetRulePrecedence returns the RulePrecedence field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetRulePrecedence() int32 {
	if o == nil || o.RulePrecedence == nil {
		var ret int32
		return ret
	}
	return *o.RulePrecedence
}

// GetRulePrecedenceOk returns a tuple with the RulePrecedence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetRulePrecedenceOk() (*int32, bool) {
	if o == nil || o.RulePrecedence == nil {
		return nil, false
	}
	return o.RulePrecedence, true
}

// HasRulePrecedence returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasRulePrecedence() bool {
	if o != nil && o.RulePrecedence != nil {
		return true
	}

	return false
}

// SetRulePrecedence gets a reference to the given int32 and assigns it to the RulePrecedence field.
func (o *AutomaticOnboardingRuleData) SetRulePrecedence(v int32) {
	o.RulePrecedence = &v
}

// GetTargetPlatformId returns the TargetPlatformId field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetTargetPlatformId() string {
	if o == nil || o.TargetPlatformId == nil {
		var ret string
		return ret
	}
	return *o.TargetPlatformId
}

// GetTargetPlatformIdOk returns a tuple with the TargetPlatformId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetTargetPlatformIdOk() (*string, bool) {
	if o == nil || o.TargetPlatformId == nil {
		return nil, false
	}
	return o.TargetPlatformId, true
}

// HasTargetPlatformId returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasTargetPlatformId() bool {
	if o != nil && o.TargetPlatformId != nil {
		return true
	}

	return false
}

// SetTargetPlatformId gets a reference to the given string and assigns it to the TargetPlatformId field.
func (o *AutomaticOnboardingRuleData) SetTargetPlatformId(v string) {
	o.TargetPlatformId = &v
}

// GetTargetDeviceType returns the TargetDeviceType field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetTargetDeviceType() string {
	if o == nil || o.TargetDeviceType == nil {
		var ret string
		return ret
	}
	return *o.TargetDeviceType
}

// GetTargetDeviceTypeOk returns a tuple with the TargetDeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetTargetDeviceTypeOk() (*string, bool) {
	if o == nil || o.TargetDeviceType == nil {
		return nil, false
	}
	return o.TargetDeviceType, true
}

// HasTargetDeviceType returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasTargetDeviceType() bool {
	if o != nil && o.TargetDeviceType != nil {
		return true
	}

	return false
}

// SetTargetDeviceType gets a reference to the given string and assigns it to the TargetDeviceType field.
func (o *AutomaticOnboardingRuleData) SetTargetDeviceType(v string) {
	o.TargetDeviceType = &v
}

// GetTargetSafeName returns the TargetSafeName field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetTargetSafeName() string {
	if o == nil || o.TargetSafeName == nil {
		var ret string
		return ret
	}
	return *o.TargetSafeName
}

// GetTargetSafeNameOk returns a tuple with the TargetSafeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetTargetSafeNameOk() (*string, bool) {
	if o == nil || o.TargetSafeName == nil {
		return nil, false
	}
	return o.TargetSafeName, true
}

// HasTargetSafeName returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasTargetSafeName() bool {
	if o != nil && o.TargetSafeName != nil {
		return true
	}

	return false
}

// SetTargetSafeName gets a reference to the given string and assigns it to the TargetSafeName field.
func (o *AutomaticOnboardingRuleData) SetTargetSafeName(v string) {
	o.TargetSafeName = &v
}

// GetIsAdminIDFilter returns the IsAdminIDFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetIsAdminIDFilter() bool {
	if o == nil || o.IsAdminIDFilter == nil {
		var ret bool
		return ret
	}
	return *o.IsAdminIDFilter
}

// GetIsAdminIDFilterOk returns a tuple with the IsAdminIDFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetIsAdminIDFilterOk() (*bool, bool) {
	if o == nil || o.IsAdminIDFilter == nil {
		return nil, false
	}
	return o.IsAdminIDFilter, true
}

// HasIsAdminIDFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasIsAdminIDFilter() bool {
	if o != nil && o.IsAdminIDFilter != nil {
		return true
	}

	return false
}

// SetIsAdminIDFilter gets a reference to the given bool and assigns it to the IsAdminIDFilter field.
func (o *AutomaticOnboardingRuleData) SetIsAdminIDFilter(v bool) {
	o.IsAdminIDFilter = &v
}

// GetMachineTypeFilter returns the MachineTypeFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetMachineTypeFilter() string {
	if o == nil || o.MachineTypeFilter == nil {
		var ret string
		return ret
	}
	return *o.MachineTypeFilter
}

// GetMachineTypeFilterOk returns a tuple with the MachineTypeFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetMachineTypeFilterOk() (*string, bool) {
	if o == nil || o.MachineTypeFilter == nil {
		return nil, false
	}
	return o.MachineTypeFilter, true
}

// HasMachineTypeFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasMachineTypeFilter() bool {
	if o != nil && o.MachineTypeFilter != nil {
		return true
	}

	return false
}

// SetMachineTypeFilter gets a reference to the given string and assigns it to the MachineTypeFilter field.
func (o *AutomaticOnboardingRuleData) SetMachineTypeFilter(v string) {
	o.MachineTypeFilter = &v
}

// GetSystemTypeFilter returns the SystemTypeFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetSystemTypeFilter() string {
	if o == nil || o.SystemTypeFilter == nil {
		var ret string
		return ret
	}
	return *o.SystemTypeFilter
}

// GetSystemTypeFilterOk returns a tuple with the SystemTypeFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetSystemTypeFilterOk() (*string, bool) {
	if o == nil || o.SystemTypeFilter == nil {
		return nil, false
	}
	return o.SystemTypeFilter, true
}

// HasSystemTypeFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasSystemTypeFilter() bool {
	if o != nil && o.SystemTypeFilter != nil {
		return true
	}

	return false
}

// SetSystemTypeFilter gets a reference to the given string and assigns it to the SystemTypeFilter field.
func (o *AutomaticOnboardingRuleData) SetSystemTypeFilter(v string) {
	o.SystemTypeFilter = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetCreationTime() int32 {
	if o == nil || o.CreationTime == nil {
		var ret int32
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetCreationTimeOk() (*int32, bool) {
	if o == nil || o.CreationTime == nil {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasCreationTime() bool {
	if o != nil && o.CreationTime != nil {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given int32 and assigns it to the CreationTime field.
func (o *AutomaticOnboardingRuleData) SetCreationTime(v int32) {
	o.CreationTime = &v
}

// GetUserNameFilter returns the UserNameFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetUserNameFilter() string {
	if o == nil || o.UserNameFilter == nil {
		var ret string
		return ret
	}
	return *o.UserNameFilter
}

// GetUserNameFilterOk returns a tuple with the UserNameFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetUserNameFilterOk() (*string, bool) {
	if o == nil || o.UserNameFilter == nil {
		return nil, false
	}
	return o.UserNameFilter, true
}

// HasUserNameFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasUserNameFilter() bool {
	if o != nil && o.UserNameFilter != nil {
		return true
	}

	return false
}

// SetUserNameFilter gets a reference to the given string and assigns it to the UserNameFilter field.
func (o *AutomaticOnboardingRuleData) SetUserNameFilter(v string) {
	o.UserNameFilter = &v
}

// GetUserNameMethod returns the UserNameMethod field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetUserNameMethod() string {
	if o == nil || o.UserNameMethod == nil {
		var ret string
		return ret
	}
	return *o.UserNameMethod
}

// GetUserNameMethodOk returns a tuple with the UserNameMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetUserNameMethodOk() (*string, bool) {
	if o == nil || o.UserNameMethod == nil {
		return nil, false
	}
	return o.UserNameMethod, true
}

// HasUserNameMethod returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasUserNameMethod() bool {
	if o != nil && o.UserNameMethod != nil {
		return true
	}

	return false
}

// SetUserNameMethod gets a reference to the given string and assigns it to the UserNameMethod field.
func (o *AutomaticOnboardingRuleData) SetUserNameMethod(v string) {
	o.UserNameMethod = &v
}

// GetAddressFilter returns the AddressFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetAddressFilter() string {
	if o == nil || o.AddressFilter == nil {
		var ret string
		return ret
	}
	return *o.AddressFilter
}

// GetAddressFilterOk returns a tuple with the AddressFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetAddressFilterOk() (*string, bool) {
	if o == nil || o.AddressFilter == nil {
		return nil, false
	}
	return o.AddressFilter, true
}

// HasAddressFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasAddressFilter() bool {
	if o != nil && o.AddressFilter != nil {
		return true
	}

	return false
}

// SetAddressFilter gets a reference to the given string and assigns it to the AddressFilter field.
func (o *AutomaticOnboardingRuleData) SetAddressFilter(v string) {
	o.AddressFilter = &v
}

// GetAddressMethod returns the AddressMethod field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetAddressMethod() string {
	if o == nil || o.AddressMethod == nil {
		var ret string
		return ret
	}
	return *o.AddressMethod
}

// GetAddressMethodOk returns a tuple with the AddressMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetAddressMethodOk() (*string, bool) {
	if o == nil || o.AddressMethod == nil {
		return nil, false
	}
	return o.AddressMethod, true
}

// HasAddressMethod returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasAddressMethod() bool {
	if o != nil && o.AddressMethod != nil {
		return true
	}

	return false
}

// SetAddressMethod gets a reference to the given string and assigns it to the AddressMethod field.
func (o *AutomaticOnboardingRuleData) SetAddressMethod(v string) {
	o.AddressMethod = &v
}

// GetAccountTypeFilter returns the AccountTypeFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetAccountTypeFilter() string {
	if o == nil || o.AccountTypeFilter == nil {
		var ret string
		return ret
	}
	return *o.AccountTypeFilter
}

// GetAccountTypeFilterOk returns a tuple with the AccountTypeFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetAccountTypeFilterOk() (*string, bool) {
	if o == nil || o.AccountTypeFilter == nil {
		return nil, false
	}
	return o.AccountTypeFilter, true
}

// HasAccountTypeFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasAccountTypeFilter() bool {
	if o != nil && o.AccountTypeFilter != nil {
		return true
	}

	return false
}

// SetAccountTypeFilter gets a reference to the given string and assigns it to the AccountTypeFilter field.
func (o *AutomaticOnboardingRuleData) SetAccountTypeFilter(v string) {
	o.AccountTypeFilter = &v
}

// GetAccountCategoryFilter returns the AccountCategoryFilter field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetAccountCategoryFilter() string {
	if o == nil || o.AccountCategoryFilter == nil {
		var ret string
		return ret
	}
	return *o.AccountCategoryFilter
}

// GetAccountCategoryFilterOk returns a tuple with the AccountCategoryFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetAccountCategoryFilterOk() (*string, bool) {
	if o == nil || o.AccountCategoryFilter == nil {
		return nil, false
	}
	return o.AccountCategoryFilter, true
}

// HasAccountCategoryFilter returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasAccountCategoryFilter() bool {
	if o != nil && o.AccountCategoryFilter != nil {
		return true
	}

	return false
}

// SetAccountCategoryFilter gets a reference to the given string and assigns it to the AccountCategoryFilter field.
func (o *AutomaticOnboardingRuleData) SetAccountCategoryFilter(v string) {
	o.AccountCategoryFilter = &v
}

// GetReconcileAccountId returns the ReconcileAccountId field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetReconcileAccountId() string {
	if o == nil || o.ReconcileAccountId == nil {
		var ret string
		return ret
	}
	return *o.ReconcileAccountId
}

// GetReconcileAccountIdOk returns a tuple with the ReconcileAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetReconcileAccountIdOk() (*string, bool) {
	if o == nil || o.ReconcileAccountId == nil {
		return nil, false
	}
	return o.ReconcileAccountId, true
}

// HasReconcileAccountId returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasReconcileAccountId() bool {
	if o != nil && o.ReconcileAccountId != nil {
		return true
	}

	return false
}

// SetReconcileAccountId gets a reference to the given string and assigns it to the ReconcileAccountId field.
func (o *AutomaticOnboardingRuleData) SetReconcileAccountId(v string) {
	o.ReconcileAccountId = &v
}

// GetLastOnboardedTime returns the LastOnboardedTime field value if set, zero value otherwise.
func (o *AutomaticOnboardingRuleData) GetLastOnboardedTime() int32 {
	if o == nil || o.LastOnboardedTime == nil {
		var ret int32
		return ret
	}
	return *o.LastOnboardedTime
}

// GetLastOnboardedTimeOk returns a tuple with the LastOnboardedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomaticOnboardingRuleData) GetLastOnboardedTimeOk() (*int32, bool) {
	if o == nil || o.LastOnboardedTime == nil {
		return nil, false
	}
	return o.LastOnboardedTime, true
}

// HasLastOnboardedTime returns a boolean if a field has been set.
func (o *AutomaticOnboardingRuleData) HasLastOnboardedTime() bool {
	if o != nil && o.LastOnboardedTime != nil {
		return true
	}

	return false
}

// SetLastOnboardedTime gets a reference to the given int32 and assigns it to the LastOnboardedTime field.
func (o *AutomaticOnboardingRuleData) SetLastOnboardedTime(v int32) {
	o.LastOnboardedTime = &v
}

func (o AutomaticOnboardingRuleData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RuleId != nil {
		toSerialize["RuleId"] = o.RuleId
	}
	if o.RuleName != nil {
		toSerialize["RuleName"] = o.RuleName
	}
	if o.RuleDescription != nil {
		toSerialize["RuleDescription"] = o.RuleDescription
	}
	if o.RulePrecedence != nil {
		toSerialize["RulePrecedence"] = o.RulePrecedence
	}
	if o.TargetPlatformId != nil {
		toSerialize["TargetPlatformId"] = o.TargetPlatformId
	}
	if o.TargetDeviceType != nil {
		toSerialize["TargetDeviceType"] = o.TargetDeviceType
	}
	if o.TargetSafeName != nil {
		toSerialize["TargetSafeName"] = o.TargetSafeName
	}
	if o.IsAdminIDFilter != nil {
		toSerialize["IsAdminIDFilter"] = o.IsAdminIDFilter
	}
	if o.MachineTypeFilter != nil {
		toSerialize["MachineTypeFilter"] = o.MachineTypeFilter
	}
	if o.SystemTypeFilter != nil {
		toSerialize["SystemTypeFilter"] = o.SystemTypeFilter
	}
	if o.CreationTime != nil {
		toSerialize["CreationTime"] = o.CreationTime
	}
	if o.UserNameFilter != nil {
		toSerialize["UserNameFilter"] = o.UserNameFilter
	}
	if o.UserNameMethod != nil {
		toSerialize["UserNameMethod"] = o.UserNameMethod
	}
	if o.AddressFilter != nil {
		toSerialize["AddressFilter"] = o.AddressFilter
	}
	if o.AddressMethod != nil {
		toSerialize["AddressMethod"] = o.AddressMethod
	}
	if o.AccountTypeFilter != nil {
		toSerialize["AccountTypeFilter"] = o.AccountTypeFilter
	}
	if o.AccountCategoryFilter != nil {
		toSerialize["AccountCategoryFilter"] = o.AccountCategoryFilter
	}
	if o.ReconcileAccountId != nil {
		toSerialize["ReconcileAccountId"] = o.ReconcileAccountId
	}
	if o.LastOnboardedTime != nil {
		toSerialize["LastOnboardedTime"] = o.LastOnboardedTime
	}
	return json.Marshal(toSerialize)
}

type NullableAutomaticOnboardingRuleData struct {
	value *AutomaticOnboardingRuleData
	isSet bool
}

func (v NullableAutomaticOnboardingRuleData) Get() *AutomaticOnboardingRuleData {
	return v.value
}

func (v *NullableAutomaticOnboardingRuleData) Set(val *AutomaticOnboardingRuleData) {
	v.value = val
	v.isSet = true
}

func (v NullableAutomaticOnboardingRuleData) IsSet() bool {
	return v.isSet
}

func (v *NullableAutomaticOnboardingRuleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutomaticOnboardingRuleData(val *AutomaticOnboardingRuleData) *NullableAutomaticOnboardingRuleData {
	return &NullableAutomaticOnboardingRuleData{value: val, isSet: true}
}

func (v NullableAutomaticOnboardingRuleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutomaticOnboardingRuleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


