/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// JsonPatchDocumentAccountModel struct for JsonPatchDocumentAccountModel
type JsonPatchDocumentAccountModel struct {
	Operations []OperationAccountModel `json:"Operations,omitempty"`
}

// NewJsonPatchDocumentAccountModel instantiates a new JsonPatchDocumentAccountModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonPatchDocumentAccountModel() *JsonPatchDocumentAccountModel {
	this := JsonPatchDocumentAccountModel{}
	return &this
}

// NewJsonPatchDocumentAccountModelWithDefaults instantiates a new JsonPatchDocumentAccountModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonPatchDocumentAccountModelWithDefaults() *JsonPatchDocumentAccountModel {
	this := JsonPatchDocumentAccountModel{}
	return &this
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *JsonPatchDocumentAccountModel) GetOperations() []OperationAccountModel {
	if o == nil || o.Operations == nil {
		var ret []OperationAccountModel
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonPatchDocumentAccountModel) GetOperationsOk() ([]OperationAccountModel, bool) {
	if o == nil || o.Operations == nil {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *JsonPatchDocumentAccountModel) HasOperations() bool {
	if o != nil && o.Operations != nil {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []OperationAccountModel and assigns it to the Operations field.
func (o *JsonPatchDocumentAccountModel) SetOperations(v []OperationAccountModel) {
	o.Operations = v
}

func (o JsonPatchDocumentAccountModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Operations != nil {
		toSerialize["Operations"] = o.Operations
	}
	return json.Marshal(toSerialize)
}

type NullableJsonPatchDocumentAccountModel struct {
	value *JsonPatchDocumentAccountModel
	isSet bool
}

func (v NullableJsonPatchDocumentAccountModel) Get() *JsonPatchDocumentAccountModel {
	return v.value
}

func (v *NullableJsonPatchDocumentAccountModel) Set(val *JsonPatchDocumentAccountModel) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonPatchDocumentAccountModel) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonPatchDocumentAccountModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonPatchDocumentAccountModel(val *JsonPatchDocumentAccountModel) *NullableJsonPatchDocumentAccountModel {
	return &NullableJsonPatchDocumentAccountModel{value: val, isSet: true}
}

func (v NullableJsonPatchDocumentAccountModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonPatchDocumentAccountModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


