/*
Privileged Access Security REST API

Display the PVWA REST APIs below for a description of how to use them and try them out. Access information about additional REST APIs through the online documentation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetPlatformsRequestBase struct for GetPlatformsRequestBase
type GetPlatformsRequestBase struct {
	Search *string `json:"Search,omitempty"`
}

// NewGetPlatformsRequestBase instantiates a new GetPlatformsRequestBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlatformsRequestBase() *GetPlatformsRequestBase {
	this := GetPlatformsRequestBase{}
	return &this
}

// NewGetPlatformsRequestBaseWithDefaults instantiates a new GetPlatformsRequestBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlatformsRequestBaseWithDefaults() *GetPlatformsRequestBase {
	this := GetPlatformsRequestBase{}
	return &this
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *GetPlatformsRequestBase) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlatformsRequestBase) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *GetPlatformsRequestBase) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *GetPlatformsRequestBase) SetSearch(v string) {
	o.Search = &v
}

func (o GetPlatformsRequestBase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Search != nil {
		toSerialize["Search"] = o.Search
	}
	return json.Marshal(toSerialize)
}

type NullableGetPlatformsRequestBase struct {
	value *GetPlatformsRequestBase
	isSet bool
}

func (v NullableGetPlatformsRequestBase) Get() *GetPlatformsRequestBase {
	return v.value
}

func (v *NullableGetPlatformsRequestBase) Set(val *GetPlatformsRequestBase) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlatformsRequestBase) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlatformsRequestBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlatformsRequestBase(val *GetPlatformsRequestBase) *NullableGetPlatformsRequestBase {
	return &NullableGetPlatformsRequestBase{value: val, isSet: true}
}

func (v NullableGetPlatformsRequestBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPlatformsRequestBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


